### PR TITLE
Make SVN::Look::proplist method work (fix regexp).

### PR DESCRIPTION
**Pull request by hartzell**
Hi gnustavo,

SVN::Look fails its tests on my Mac running OS X 10.8.4, using the builtin svn (1.6.18) and the newer one that I built using homebrew (1.8.0).  I'm not sure if the output from `proplist --verbose` has changed since you wrote the code or....

In any case, I've updated the regexp that you use to split the output and it now Works For Me (tm).

It would be great if you could roll out a new release (with this fix or a better one...) so that out CI builds can Just Work (tm).

Thanks,

g.

---

The split in proplist should take output from svn proplist --verbose,
which looks like this on svn version 1.6 and 1.8:

---

Properties on 'foo':
  svn:mime-type
    text/plain
  svn:blarney
    text/plain

---

 and parse it into  list whose elements are:

---

Properties on 'foo':
svn:mime-type
text/plain
svn:blarney
text/plain

---

The method then goes on and discards the first element of the list and
the remaining are chomped and used to create the hash.

### CODE REVIEW

**Comment by gnustavo** [comment]
Thanks George, but I think there is a misunderstanding here. The syntax you showed is for the command "svn proplist", as you mentioned. But the SVN::Look code invokes the command "svnlook proplist" in the server, instead. The syntax of which is like this:

```
$ svnlook proplist . trunk/jira/jira-dump.pl --verbose
  svn:eol-style : native
  svn:executable : *
  svn:mime-type : text/x-perl
  svn:keywords : "Author Date Id Rev URL"
```

Anyway, I'd like to take a look at the error message you're getting during SVN::Look tests.

## 

Gustavo.

**Comment by hartzell** [comment]
Gustavo Chaves writes:

> Thanks George, but I think there is a misunderstanding here. The syntax you showed is for the command "svn proplist", as you mentioned. But the SVN::Look code invokes the command "svnlook proplist" in the server, instead. The syntax of which is like this:
> 
> ```
> $ svnlook proplist . trunk/jira/jira-dump.pl --verbose
>   svn:eol-style : native
>   svn:executable : *
>   svn:mime-type : text/x-perl
>   svn:keywords : "Author Date Id Rev URL"
> ```
> 
> Anyway, I'd like to take a look at the error message you're getting during SVN::Look tests.

Ok, this is odd....

I went down this path because SVN::Look (CPAN and your github version)
fail a couple of tests in 01-commands.t (test 8 and 9)

Here's a little debug session and comments, sections deliniated by
dashed lines.

First time through, stop at line 54 just to get close, then break on
SVN::Look::proplist.

Notice that the text that is returned looks just like the svn proplist
output, not like the output you expect.

  DB<1> b 54
  DB<2> c
1..14
ok 1 - constructor
ok 2 - grok author
ok 3 - author
ok 4 - log_msg
ok 5 - added
ok 6 - diff
main::(t/01-commands.t:54): $look = SVN::Look->new($repo);
  DB<2> n
main::(t/01-commands.t:56): my $pl = eval { $look->proplist('a b.txt') };
  DB<2> b SVN::Look::proplist
  DB<3> c
SVN::Look::proplist(lib/SVN/Look.pm:501):
501:        my ($self, $path) = @_;
  DB<3> n
SVN::Look::proplist(lib/SVN/Look.pm:502):
502:        unless ($self->{proplist}{$path}) {
  DB<3> n
SVN::Look::proplist(lib/SVN/Look.pm:503):
503:            my $text = $self->_svnlook('proplist', '--verbose', $path);
  DB<3> n
SVN::Look::proplist(lib/SVN/Look.pm:504):
504:            my @list = split /^\s\s(\S+)\s:\s/m, $text;
  DB<3> x $text
0  'Properties on \'/a b.txt\':
  svn:mime-type
    text/plain
'
  DB<4> x $self
0  SVN::Look=HASH(0x7fe5116bfee0)
   'opts' => ARRAY(0x7fe511a34408)
        empty array
   'proplist' => HASH(0x7fe511a34240)
        empty hash
   'repo' => '/Users/hartzell/projects/SVN-Look/t.Q9ab/repo'

---

Next step, walk into _svnlook and see what the command looks like.

And it look like

  svnlook proplist /Users/hartzell/projects/SVN-Look/t.idb_/repo "--verbose" "a b.txt" |

Cut that out, stop the debugger and run it at my shell and I get
output that looks just like the svn proplist command.  Step through a
bit more and the output from my command line matches what the method
generates.

  DB<8> n
SVN::Look::_svnlook(lib/SVN/Look.pm:85):
85:     my @cmd = ('svnlook', $cmd, $self->{repo});
  DB<8> x $cmd
0  'proplist'
  DB<9> n
SVN::Look::_svnlook(lib/SVN/Look.pm:86):
86:     push @cmd, @{$self->{opts}} unless $cmd =~ /^(?:youngest|uuid|lock)$/;
  DB<9>
SVN::Look::_svnlook(lib/SVN/Look.pm:86):
86:     push @cmd, @{$self->{opts}} unless $cmd =~ /^(?:youngest|uuid|lock)$/;
  DB<9>
SVN::Look::_svnlook(lib/SVN/Look.pm:87):
87:     my $args = @args ? '"' . join('" "', @args) . '"' : '';
  DB<9> n
SVN::Look::_svnlook(lib/SVN/Look.pm:88):
88:     open my $fd, join(' ', @cmd, $args, '|') ## no critic (InputOutput::ProhibitTwoArgOpen)
89:         or die "Can't exec svnlook $cmd: $!\n";
  DB<9> x join(' ', @cmd, $args, '|')
0  'svnlook proplist /Users/hartzell/projects/SVN-Look/t.idb_/repo "--verbose" "a b.txt" |'
  DB<10> ^Z
[1]+  Stopped                 perl -d -Ilib t/01-commands.t
devmac2:SVN-Look hartzell$ svnlook proplist /Users/hartzell/projects/SVN-Look/t.idb_/repo "--verbose" "a b.txt"
Properties on '/a b.txt':
  svn:mime-type
    text/plain
devmac2:SVN-Look hartzell$ fg
perl -d -Ilib t/01-commands.t
n
SVN::Look::_svnlook(lib/SVN/Look.pm:90):
90:     if (wantarray) {
  DB<10> n
SVN::Look::_svnlook(lib/SVN/Look.pm:103):
103:            local $/ = undef;
  DB<10>
SVN::Look::_svnlook(lib/SVN/Look.pm:104):
104:            my $line = <$fd>;
  DB<10>
SVN::Look::_svnlook(lib/SVN/Look.pm:105):
105:            unless (close $fd) {
  DB<10>
SVN::Look::_svnlook(lib/SVN/Look.pm:112):
112:            chomp $line unless $cmd eq 'cat';
  DB<10>
SVN::Look::_svnlook(lib/SVN/Look.pm:113):
113:            return $line;
  DB<10> x $line
0  'Properties on \'/a b.txt\':
  svn:mime-type
    text/plain
'
  DB<11>

---

And finally, here's a bit of info about my subversion install (it
should be the bog standard homebrew config for a mac running os x
10.8.4).

devmac2:SVN-Look hartzell$ which svn
/usr/local/bin/svn
devmac2:SVN-Look hartzell$ svn --version
svn, version 1.8.0 (r1490375)
   compiled Aug 27 2013, 15:45:30 on x86_64-apple-darwin12.4.0

Copyright (C) 2013 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:
- ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
- ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
- ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - handles 'http' scheme
  - handles 'https' scheme

devmac2:SVN-Look hartzell$ which svnlook
/usr/local/bin/svnlook
devmac2:SVN-Look hartzell$ svnlook --version
svnlook, version 1.8.0 (r1490375)
   compiled Aug 27 2013, 15:45:30 on x86_64-apple-darwin12.4.0

Copyright (C) 2013 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository back-end (FS) modules are available:
- fs_fs : Module for working with a plain file (FSFS) repository.

---

What version of svn are you running?  What platform?

Thanks for looking in to this!

g.

**Comment by hartzell** [comment]
Gustavo Chaves writes:

> Thanks George, but I think there is a misunderstanding here. The
> syntax you showed is for the command "svn proplist", as you
> mentioned. But the SVN::Look code invokes the command "svnlook
> proplist" in the server, instead. The syntax of which is like this: 

Looks like the output format of svnlook proplist changed changed in
between 1.6 and 1.8:

   http://mail-archives.apache.org/mod_mbox/subversion-dev/201212.mbox/%3CCAO16vNSCbfeNTQetSZKEuU1pfj-gZoXQ9mujHMbed-uqQrSsJQ@mail.gmail.com%3E

g.

**Comment by gnustavo** [comment]
2013/8/31 George Hartzell notifications@github.com

> Looks like the output format of svnlook proplist changed changed in
> between 1.6 and 1.8:
> 
> http://mail-archives.apache.org/mod_mbox/subversion-dev/201212.mbox/%3CCAO16vNSCbfeNTQetSZKEuU1pfj-gZoXQ9mujHMbed-uqQrSsJQ@mail.gmail.com%3E

You're right! I'm not using Subversion 1.8 yet, so I haven't noticed it.

I guess the best thing to do would be to use the --xml svnlook option, but
I'll have to see if it always existed.

I'll try to come up with a working version soon.

Thank you very much.

## 

Gustavo.

**Comment by hartzell** [comment]
Gustavo Chaves writes:

> 2013/8/31 George Hartzell notifications@github.com
> 
> > Looks like the output format of svnlook proplist changed changed in
> > between 1.6 and 1.8:
> > 
> > http://mail-archives.apache.org/mod_mbox/subversion-dev/201212.mbox/%3CCAO16vNSCbfeNTQetSZKEuU1pfj-gZoXQ9mujHMbed-uqQrSsJQ@mail.gmail.com%3E
> 
> You're right! I'm not using Subversion 1.8 yet, so I haven't noticed it.
> 
> I guess the best thing to do would be to use the --xml svnlook option, but
> I'll have to see if it always existed.
> 
> I'll try to come up with a working version soon.

Worst case you could either set a version variable in new or fire off
a quick --version check....

Let me know if you want a tester.

g.

**Comment by gnustavo** [comment]
George, I've tried to fix this. I'm not completely satisfied, but I think it works. Can you give it a try?

You can grab the new version from [here](https://docs.google.com/file/d/0B9L-BReu8J7ERFdSUVNmNkhjcU0/edit?usp=sharing).

Thanks.

Gustavo.

**Comment by hartzell** [comment]
Gustavo Chaves writes:

> George, I've tried to fix this. I'm not completely satisfied, but I
> think it works. Can you give it a try? 
> [...]

I'll try during the week, definitely over the weekend.  Thanks for
working on it!

g.

**Comment by hartzell** [comment]
Hi Gustavo,

Apologies for the delay.

This works for me on Perl 5.16.2 and 5.18.0 on Mac OS X 10.8.5.

I'd love to see it make it out.

Thanks,

g.

**Comment by gnustavo** [comment]
2013/10/19 George Hartzell notifications@github.com

> Hi Gustavo,
> 
> Apologies for the delay.
> 
> This works for me on Perl 5.16.2 and 5.18.0 on Mac OS X 10.8.5.
> 
> I'd love to see it make it out.

Hi George. I've just uploaded v0.39 to PAUSE. It should appear on CPAN
shortly.

## 

Gustavo.

**Pull request closed without merging**
